AY2324S2-CS2113-F15-2/tp

src/main/java/seedu/lifetrack/LifeTrack.java, src/main/java/seedu/lifetrack/calories/activity/Activity.java, src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/calories/calorielist/Entry.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java, src/main/java/seedu/lifetrack/system/parser/Parser.java, src/main/java/seedu/lifetrack/ui/Ui.java, src/test/java/seedu/lifetrack/CalorieListTest.java, src/test/java/seedu/lifetrack/InputTest.java, src/test/java/seedu/lifetrack/LifeTrackTest.java
Cleaned up code for better handling of exceptions and organization of files.
=> Create final changes for v1.0

src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
Added some assertions in the parseCaloriesInput method to ensure that compulsory keywords provided in "calories in" and "calories out" commands are present
=> add assertions for parseCaloriesInput

src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/system/Ui.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java, src/main/java/seedu/lifetrack/system/parser/ParserCalories.java, src/main/java/seedu/lifetrack/system/parser/ParserLiquid.java, src/test/java/seedu/lifetrack/CalorieListTest.java, src/test/java/seedu/lifetrack/LifeTrackTest.java
Add exceptions
1. Exception for keying in macro field correctly
2. Exception for ensuring all macronutrients have been typed in
3. Exception for keying in macros with spaces in inputs
4. Exception for ensuring that there are no blanks in macronutrients fields
5. Exception to handle case where calories out commands are entered in wrong order
6. Exception to handle case where calories in commands are entered in wrong order
7. Exception to handle unexpected case of keying in macros for calories out
=> Add more exception handling for Class ParserCalories.java

src/main/java/seedu/lifetrack/LifeTrack.java, src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/calories/calorielist/Entry.java, src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java, src/main/java/seedu/lifetrack/system/parser/Parser.java, src/main/java/seedu/lifetrack/ui/CalorieListUi.java, src/main/java/seedu/lifetrack/ui/Ui.java, src/test/java/seedu/lifetrack/LifeTrackTest.java
reorganised the app,
added help command
improved the UI of the app
reflected these changes in test cases
=> Beautify the App 

src/test/java/seedu/lifetrack/CalorieListTest.java, src/test/java/seedu/lifetrack/LiquidListTest.java, src/test/java/seedu/lifetrack/ParserLiquidTest.java
after the JUnit test code was re-organised, multiple new files were created to organise test code based on class level. however, this had an unintended consequence of changing the authoring of the code, this PR is meant to resolve that issue and reset the original authors as the rightful authors of the code
=> set authors for original writers of JUnit test code

src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidList.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java, src/main/java/seedu/lifetrack/ui/CalorieListUi.java
=> Fix logger

src/main/java/seedu/lifetrack/LifeTrack.java, src/main/java/seedu/lifetrack/sleep/Sleep.java, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java, src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java, src/main/java/seedu/lifetrack/system/parser/ParserSleep.java, src/main/java/seedu/lifetrack/ui/SleepListUi.java, src/main/java/seedu/lifetrack/ui/Ui.java, src/test/java/seedu/lifetrack/ParserSleepTest.java, src/test/java/seedu/lifetrack/SleepListTest.java, src/test/java/seedu/lifetrack/UITest.java
Add Sleep feature, including updating UI, LifeTraker, Praser and Test
=> Add Sleep Feature

src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java, src/main/java/seedu/lifetrack/system/parser/ParserLiquid.java, src/test/java/seedu/lifetrack/ParserLiquidTest.java
In Class InvalidInputExceptionMessage.java , add methods with custom exception messages. 
Add getHydrationMissingKeywordMessage()
Add getHydrationIncorrectOrderMessage()
Add getHydrationEmptyDescriptionMessage()
Add getHydrationNonIntegerVolumeMessage()
=> Tidy up hydration exception messages

.gitignore, docs/DeveloperGuide.md
added some documentation for ParserCalories in the DG
=> Add DG details for ParserCalories

src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java, src/main/java/seedu/lifetrack/ui/Ui.java, src/test/java/seedu/lifetrack/ParserHydrationTest.java
updated help command to reflect new and updated commands, as well as the expected `hydration add` input in the `InvalidInputExceptionMessage` class.
=> update help command output and exception messages

src/main/java/seedu/lifetrack/Entry.java, src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java, src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java, src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationEntry.java, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java, src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java, src/main/java/seedu/lifetrack/system/parser/ParserCalories.java, src/main/java/seedu/lifetrack/system/parser/ParserHydration.java, src/main/java/seedu/lifetrack/system/parser/ParserSleep.java, src/main/java/seedu/lifetrack/system/storage/FileHandler.java, src/main/java/seedu/lifetrack/ui/Ui.java, src/test/java/seedu/lifetrack/CalorieListTest.java, src/test/java/seedu/lifetrack/HydrationListTest.java, src/test/java/seedu/lifetrack/ParserCaloriesTest.java, src/test/java/seedu/lifetrack/ParserHydrationTest.java, src/test/java/seedu/lifetrack/ParserSleepTest.java, src/test/java/seedu/lifetrack/SleepListTest.java
Add date format using Java Class LocalDate
Add LocalDate for Calories feature
Add LocalDate for Hydration feature
Add LocalDate for Sleep feature
Edit JUnit tests to follow LocalDate format
=> Add date format for Calories, Hydration and Sleep

src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java, src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java, src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java, src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
Add javdocs for Calories related Classes
The following are the Classes covered under this Pull Request
1. CalorieList
2. ParserCalories
3. InvalidInputException
4. ErrorMessages
5. InvalidInputExceptionMessages
6. InputEntry
7. OutputEntry
=> Add javadocs for Calories

docs/UserGuide.md
Add quick links
Add calories in details
Add calories out details
Add calories list details
Add command summary
=> Edit user UserGuide

src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java, src/main/java/seedu/lifetrack/system/parser/ParserUser.java, src/main/java/seedu/lifetrack/ui/Ui.java, src/main/java/seedu/lifetrack/ui/UserUi.java, src/main/java/seedu/lifetrack/user/User.java, src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Replaced API with manual calculations, and added more exception handling for `user ` inputs.
=> Replace API with Manual Calculation

src/main/java/seedu/lifetrack/Entry.java, src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java, src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java, src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationEntry.java, src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java, src/main/java/seedu/lifetrack/system/parser/ParserCalories.java, src/main/java/seedu/lifetrack/system/parser/ParserHydration.java, src/main/java/seedu/lifetrack/system/parser/ParserSleep.java, src/main/java/seedu/lifetrack/system/storage/FileHandler.java, src/main/java/seedu/lifetrack/ui/CalorieListUi.java, src/test/java/seedu/lifetrack/CalorieListTest.java, src/test/java/seedu/lifetrack/HydrationListTest.java, src/test/java/seedu/lifetrack/ParserCaloriesTest.java, src/test/java/seedu/lifetrack/ParserHydrationTest.java, src/test/java/seedu/lifetrack/ParserSleepTest.java
As a busy student I can delete my calories entries based on the entry id so that I can delete entries based on entry id, instead of based on array list index.
Add feature for new entries to have entryID. 
Add feature for entryID to be read off txt file, and written to txt file for storage.
Add feature to delete calorieList entry based on entryID
=> Add entryID into Class CalorieList

src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/ui/CalorieListUi.java, src/test/java/seedu/lifetrack/CalorieListTest.java
As a busy student I can see my daily calories burned and consumed at a glance so that I know my caloric intake and outflow.
When calories list is called, user can see a breakdown of calories inflow and calories outflow.
=> Add distinction between calories output feature

docs/UserGuide.md, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java, src/main/java/seedu/lifetrack/ui/SleepListUi.java, src/test/java/seedu/lifetrack/SleepListTest.java
Add sleep id into sleep print list
=> Add sleep id into sleep print list

src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/ui/CalorieListUi.java, src/test/java/seedu/lifetrack/CalorieListTest.java
As a busy student I can see my calorie input and output sorted according to days so that I can see what my calorie intake and outflow for each day is
Whenever user inputs new entry, dates will be checked. If new date added is earlier then the last entry's date, calorie list will be sorted according to date. 
Add JUnit tests as well.
=> Add sort entries by date feature

src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java, src/main/java/seedu/lifetrack/system/parser/ParserSleep.java, src/test/java/seedu/lifetrack/SleepListTest.java
fix sleep add cannot add future date and delete msg for empty list
=> fix sleep add cannot add future date and delete msg for empty list

docs/team/paturikarthik.md
=> Karthik-PPP-Draft

docs/team/rexyyong.md, docs/team/shawnpong.md, src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java, src/main/java/seedu/lifetrack/system/parser/ParserHydration.java, src/main/java/seedu/lifetrack/ui/HydrationListUI.java, src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java, src/test/java/seedu/lifetrack/HydrationListTest.java
Fix user progress to show current day calories and hydration.
Added PPP for myself
=> User progress filtered by date

src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java, src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java, src/main/java/seedu/lifetrack/system/parser/ParserUser.java, src/main/java/seedu/lifetrack/ui/Ui.java, src/main/java/seedu/lifetrack/ui/UserUi.java, src/main/java/seedu/lifetrack/user/User.java, src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Added a 3 day Summary of Calories, Sleep and Hydration for User Progress Command
=> Add 3 day Summary of Calories, Sleep and Hydration

src/main/java/seedu/lifetrack/system/parser/ParserUser.java
Add ability to read in names from users with special characters in their name
=> Add ability to read in names from users with special characters in their name

src/main/java/seedu/lifetrack/system/parser/ParserCalories.java, src/test/java/seedu/lifetrack/ParserCaloriesTest.java
disallowed negative inputs for macronutrients in `calories in` command, also added some correct input JUnit test cases for ParserCalories
=> final enhancements to app

src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java, src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java, src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java, src/main/java/seedu/lifetrack/system/parser/ParserCalories.java, src/main/java/seedu/lifetrack/ui/CalorieListUi.java, src/test/java/seedu/lifetrack/CalorieListTest.java, src/test/java/seedu/lifetrack/SleepListTest.java
1. Fix exception message for calories delete
2. Fix sorting of sleep list
3. Fix exception messages printed twice for non integer calories
4. Add limit of 5k calories per entry for calories in and calories out
5. Sleep duration from 1 dp to 2 dp
=> Fix internal testing issue for Rex

src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java, src/test/java/seedu/lifetrack/SleepListTest.java
=> fixed sleep fail to add issue
